# docker-compose.yaml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dart_frog_app
    ports:
      - "8080:8080"
    environment:
      - DART_ENV=production
      - PORT=8080
      # Firebase Configuration
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-credentials.json
    volumes:
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - dart_frog_network

networks:
  dart_frog_network:
    name: dart_frog_network
    driver: bridge